name = "Developers Dungeon SMP"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "292ab6caa96c2be49fadd0710cf4e6cae82e0b26e65bd378514a6be9903fdfe7"

[versions]
fabric = "0.16.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
